// Generated by CoffeeScript 1.7.1
require(['RamsAndSheep', 'RamsAndSheepUI', 'jquery', 'Storage'], function(RamsAndSheep, UI, $, Storage) {
  var container, endGame, gameManager, makeGuess, startNewGame, updateHighScores;
  container = new UI('#game');
  gameManager = new RamsAndSheep();
  updateHighScores = function(score) {
    var highScores, name, storage;
    name = $('.hi-score-name').val();
    storage = new Storage();
    highScores = storage.getStorage();
    highScores = gameManager.updateHighScores({
      name: name,
      score: score
    }, highScores);
    storage.setStorage(highScores);
    container.drawHighScores(highScores);
    return $('.restart-game').focus().click(startNewGame);
  };
  endGame = function(score) {
    container.drawWinScreen(score);
    $('.add-name').click(function() {
      return updateHighScores(score);
    });
    return $('.hi-score-name').focus().keypress(function(key) {
      if (key.which === 13) {
        return $('.add-name').focus().click();
      }
    });
  };
  makeGuess = function() {
    var guessedNumber, result;
    guessedNumber = $('.input').val();
    $('.input').val('');
    if (gameManager.isNumberValid(guessedNumber)) {
      result = gameManager.makeGuess(guessedNumber);
      container.drawGuess(guessedNumber, result);
      if (result.rams === 4) {
        return endGame(gameManager.getGuesses());
      }
    } else {
      return container.drawError(guessedNumber);
    }
  };
  startNewGame = function() {
    gameManager.startGame();
    container.drawGameScreen();
    $('.btn-make-guess').click(makeGuess);
    return $('.input').focus().keypress(function(key) {
      if (key.which === 13) {
        return $('.btn-make-guess').click();
      }
    });
  };
  container.drawStartScreen();
  return $('.btn-start-new-game').focus().click(startNewGame);
});

//# sourceMappingURL=app.map
