// Generated by CoffeeScript 1.7.1
define(function() {
  require.config({
    paths: {
      'jquery': 'libs/jquery/dist/jquery.min',
      'httpRequester': 'httpRequester',
      'Persister': 'Persister',
      'sammy': 'libs/sammy/lib/sammy',
      'Controller': 'Controller'
    }
  });
  return require(['sammy', 'Controller'], function(Sammy, Controller) {
    var app, appController;
    appController = new Controller('#wrapper');
    appController.addEvents();
    app = Sammy('#wrapper', function() {
      this.get("#/", function() {
        return appController.loadMainPage();
      });
      this.get("#/students", function() {
        return appController.loadMainPage(function() {
          return appController.loadStudentsPage();
        });
      });
      this.get("#/delete", function() {
        return appController.loadMainPage(function() {
          return appController.deleteStudentPage();
        });
      });
      return this.get("#/add", function() {
        return appController.loadMainPage(function() {
          return appController.addStudentPage();
        });
      });
    });
    return app.run('#/');
  });
});

//# sourceMappingURL=app.map
