// Generated by CoffeeScript 1.7.1
define(['httpRequester'], function(httpRequester) {
  var Persister;
  return Persister = (function() {
    function Persister(url) {
      this.url = url;
    }

    Persister.prototype.getStudents = function() {
      return httpRequester.getJSON(this.url);
    };

    Persister.prototype.addStudent = function(student) {
      return httpRequester.postJSON(this.url, student);
    };

    Persister.prototype.deleteStudent = function(id) {
      return httpRequester.deleteJSON(this.url + ("/" + id));
    };

    return Persister;

  })();
});

//# sourceMappingURL=persister.map
