// Generated by CoffeeScript 1.7.1
define(function() {
  require.config({
    paths: {
      'jquery': 'libs/jquery/dist/jquery.min',
      'httpRequester': 'httpRequester'
    }
  });
  return require(['jquery', 'httpRequester'], function($, httpRequester) {
    var getData, renderStudents;
    renderStudents = function(data) {
      var list, parsedData, student, _i, _len;
      parsedData = JSON.parse(data);
      list = $('<ul />');
      for (_i = 0, _len = parsedData.length; _i < _len; _i++) {
        student = parsedData[_i];
        list.append('<li>' + student.fname + ' ' + student.lname + ':' + ' ' + student.marks + '</li>');
      }
      return $('#results').append(list);
    };
    getData = function() {
      return httpRequester.getJSON('scripts/data.js').then(function(data) {
        return renderStudents(data);
      });
    };
    return $('#get-results-btn').click(getData);
  });
});

//# sourceMappingURL=app.map
