// Generated by CoffeeScript 1.7.1
define(['chai', 'httpRequester'], function(chai, httpRequester) {
  var should;
  should = chai.should();
  return describe("httpRequester getJSON", function() {
    it("should return promise", function() {
      return httpRequester.getJSON().should.respondTo('then');
    });
    it("should return error with no data", function() {
      return httpRequester.getJSON().then((function() {}), function(error, status) {
        return status.should.be.gt(200);
      });
    });
    return it("should return data with correct url", function() {
      var response;
      response = '[ { "fname": "George", "lname": "Todorov", "marks": "4, 5, 6" }, { "fname": "Ivan", "lname": "Ivanov", "marks": "4, 5, 6" }, { "fname": "Petrov", "lname": "Georgiev", "marks": "4, 5, 6" }, { "fname": "Stamat", "lname": "Petrov", "marks": "4, 5, 6" }, { "fname": "Nikolay", "lname": "Nikolov", "marks": "4, 5, 6" }, { "fname": "Jana", "lname": "Todorova", "marks": "4, 5, 6" }, { "fname": "Maria", "lname": "Ivanova", "marks": "4, 5, 6" }, { "fname": "Ina", "lname": "Georgieva", "marks": "4, 5, 6" }, { "fname": "Denitsa", "lname": "Petrova", "marks": "4, 5, 6" }, { "fname": "Kameliya", "lname": "Georgieva", "marks": "4, 5, 6" } ]';
      return httpRequester.getJSON('../scripts/data.js').then((function(data) {
        return data.should.equal(response);
      }), function(error) {});
    });
  });
});

//# sourceMappingURL=httpRequester.tests.map
