// Generated by CoffeeScript 1.7.1
define(function() {
  require.config({
    paths: {
      'jquery': 'libs/jquery/dist/jquery.min',
      'httpRequester': 'httpRequester',
      'persisters': 'persisters',
      'sammy': 'libs/sammy/lib/sammy',
      'Controller': 'controller',
      'handlebars': 'libs/handlebars/handlebars-v1.3.0',
      'underscore': 'libs/underscore/underscore',
      'ui': 'ui'
    },
    shim: {
      "handlebars": {
        exports: "Handlebars"
      },
      "underscore": {
        exports: '_'
      }
    }
  });
  return require(['sammy', 'Controller'], function(Sammy, Controller) {
    var app, appController;
    appController = new Controller('#wrapper');
    appController.addEvents();
    app = Sammy('#wrapper', function() {
      return this.get("#/", function() {
        return appController.loadMainPage();
      }, this.get("#/post", function() {
        return appController.loadMainPage(function() {
          return appController.loadPostsPage();
        });
      }, this.get("#/register", function() {
        return appController.loadMainPage(function() {
          return appController.loadRegisterPage();
        });
      }, this.get("#/login", function() {
        return appController.loadMainPage(function() {
          return appController.loadLoginPage();
        });
      }))));
    });
    return app.run('#/');
  });
});

//# sourceMappingURL=app.map
