// Generated by CoffeeScript 1.7.1
define(['jquery', 'persisters', 'handlebars'], function($, persisters, Handlebars) {
  var Controller;
  return Controller = (function() {
    var url;

    url = 'http://localhost:3000';

    function Controller(selector) {
      this.selector = $(selector);
      this.persisters = persisters.get(url);
    }

    Controller.prototype.addEvents = function() {
      var self;
      self = this;
      this.selector.on('click', '#register-link', function() {
        return window.location = '#/register';
      });
      this.selector.on('click', '#btn-register', function() {
        var user;
        user = {
          username: self.selector.find('#tb-register-username').val(),
          password: self.selector.find('#tb-register-password').val()
        };
        return self.persisters.user.register(user).then(function(data) {
          var successMsg;
          successMsg = $('<div />').addClass('successMessage').text("User " + user.username + " registered!");
          return self.selector.find('.forms').append(successMsg.fadeIn(3000).fadeOut(3000));
        }, function(error) {
          var errorMsg;
          errorMsg = $('<div />').addClass('errorMessage').text("Something went wrong!");
          return self.selector.find('.forms').append(errorMsg.fadeIn(3000).fadeOut(3000));
        });
      });
      this.selector.on('click', '#logout-link', function() {
        return self.persisters.user.logout().then(function(data) {
          var successMsg;
          successMsg = $('<div />').addClass('successMessage').text("User " + user.username + " logouted!");
          return self.selector.find('.forms').append(successMsg.fadeIn(3000).fadeOut(3000));
        }, function(error) {
          var errorMsg;
          errorMsg = $('<div />').addClass('errorMessage').text("Something went wrong!");
          return self.selector.find('.forms').append(errorMsg.fadeIn(3000).fadeOut(3000));
        });
      });
      this.selector.on('click', '#btn-login', function() {
        var user;
        user = {
          username: self.selector.find('#tb-login-username').val(),
          password: self.selector.find('#tb-login-password').val()
        };
        return self.persisters.user.login(user).then(function(data) {
          var postForm, successMsg;
          successMsg = $('<div />').addClass('successMessage').text("User " + user.username + " loged in!");
          self.selector.find('.forms').append(successMsg.fadeIn(3000).fadeOut(3000));
          self.selector.find('#register-link').hide();
          self.selector.find('#login-link').hide();
          self.selector.find('#login-form').hide();
          persisters.saveUserData(data);
          postForm = $('<div>').append($('<div>').text('Post Title'));
          postForm.append($('<input>').addClass('post-title'));
          postForm.append($('<div>').text('Post Body'));
          postForm.append($('<input>').addClass('post-body'));
          postForm.append($('<button>').addClass('post-bt').text('Add Post'));
          return self.selector.find('.posts').prepend(postForm);
        }, function(error) {
          var errorMsg;
          errorMsg = $('<div />').addClass('errorMessage').text("Something went wrong!");
          return self.selector.find('.forms').append(errorMsg.fadeIn(3000).fadeOut(3000));
        });
      });
      this.selector.on('click', '.post-bt', function() {
        var post;
        post = {
          title: self.selector.find('.post-title').val(),
          body: self.selector.find('.post-body').val()
        };
        return self.persisters.post.createPost(post).then(function(data) {
          var successMsg;
          successMsg = $('<div />').addClass('successMessage').text("Post created!");
          self.selector.find('.forms').append(successMsg.fadeIn(3000).fadeOut(3000));
          return self.loadMainPage();
        }, function(error) {
          var errorMsg;
          errorMsg = $('<div />').addClass('errorMessage').text("Something went wrong!");
          return self.selector.find('.forms').append(errorMsg.fadeIn(3000).fadeOut(3000));
        });
      });
      return false;
    };

    Controller.prototype.loadMainPage = function(callback) {
      this.selector.load('../view/partials/main.html', callback);
      if (this.persisters.isUserLoggedIn()) {
        $('#register-link').hide();
        $('#login-link').hide();
      }
      return this.loadPostsPage();
    };

    Controller.prototype.loadPostsPage = function() {
      var self;
      if (this.persisters.isUserLoggedIn()) {
        $('#register-link').hide();
        $('#login-link').hide();
      }
      this.selector.find('.posts').empty();
      self = this;
      return this.persisters.post.getAllPosts().then(function(data) {
        return $.get('../view/partials/posts.html', function(partial) {
          var postTemplate, postTemplateHTML;
          postTemplateHTML = $(partial).html();
          postTemplate = Handlebars.compile(postTemplateHTML);
          return self.selector.find('.posts').html(postTemplate(data));
        });
      }, function(error) {
        var errorMsg;
        errorMsg = $('<div />').addClass('errorMessage').text("Something went wrong!");
        return self.selector.find('.posts').append(errorMsg.fadeIn(3000).fadeOut(3000));
      });
    };

    Controller.prototype.loadRegisterPage = function() {
      this.selector.find('.forms').empty();
      return this.selector.find('.forms').load("../view/partials/login.html #register-form");
    };

    Controller.prototype.loadLoginPage = function() {
      if (this.persisters.isUserLoggedIn()) {
        $('#register-link').hide();
        $('#login-link').hide();
      }
      this.selector.find('.forms').empty();
      return this.selector.find('.forms').load("../view/partials/login.html #login-form");
    };

    return Controller;

  })();
});

//# sourceMappingURL=controller.map
