// Generated by CoffeeScript 1.7.1
define(['jquery'], function($) {
  var httpRequester;
  return httpRequester = (function() {
    var getJSON, makeHTTPRequest, postJSON, putJSON;
    makeHTTPRequest = function(url, type, data, headers) {
      var promise;
      return promise = new RSVP.Promise(function(resolve, reject) {
        return $.ajax({
          url: url,
          type: type,
          headers: headers,
          data: JSON.stringify(data),
          contentType: "application/json",
          timeout: 5000,
          success: function(resultData) {
            return resolve(resultData);
          },
          error: function(errorData) {
            return reject(errorData);
          }
        });
      });
    };
    getJSON = function(url) {
      return makeHTTPRequest(url, 'GET');
    };
    postJSON = function(url, data, headers) {
      if (headers) {
        return makeHTTPRequest(url, 'POST', data, headers);
      } else {
        return makeHTTPRequest(url, 'POST', data);
      }
    };
    putJSON = function(url, headers) {
      return makeHTTPRequest(url, 'PUT', "", headers);
    };
    return {
      putJSON: putJSON,
      getJSON: getJSON,
      postJSON: postJSON
    };
  })();
});

//# sourceMappingURL=httpRequester.map
