// Generated by CoffeeScript 1.7.1
define(['jquery', 'handlebars'], function($, Handlebars) {
  var UI;
  return UI = (function() {
    function UI() {}

    UI.prototype.renderUI = function(selector, data) {
      console.log('in');
    };

    UI.prototype.renderError = function(selector, error) {};

    return UI;

  })();
});

//# sourceMappingURL=ui.map
