// Generated by CoffeeScript 1.7.1
define(['todo-list/item'], function(Item) {
  'use strict';
  var Section;
  Section = (function() {
    function Section(title) {
      this.title = title;
      this.items = [];
    }

    Section.prototype.add = function(item) {
      if (!(item instanceof Item)) {
        throw new Error("You can add only items!");
      }
      this.items.push(item);
      return this;
    };

    Section.prototype.getData = function() {
      var item, sectionItems;
      sectionItems = (function() {
        var _i, _len, _ref, _results;
        _ref = this.items;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          _results.push(item.getData);
        }
        return _results;
      }).call(this);
      return {
        title: this.title,
        items: sectionItems
      };
    };

    return Section;

  })();
  return Section;
});

//# sourceMappingURL=section.map
