// Generated by CoffeeScript 1.7.1
define(function() {
  require.config({
    paths: {
      'jquery': '../scripts/libs/jquery/dist/jquery.min',
      'httpRequester': '../scripts/httpRequester',
      'mocha': "../scripts/libs/mocha/mocha",
      'chai': "../scripts/libs/chai/chai"
    }
  });
  return require(['mocha', 'chai'], function() {
    mocha.setup('bdd');
    return require(['../tests/httpRequester.tests'], function() {
      return mocha.run();
    });
  });
});

//# sourceMappingURL=main-tests.map
